### PR TITLE
Add heed to the Other Databases list

### PR DESCRIPTION
**Pull request by Kerollmops**
Hello 👋

This PR adds heed to the list of Other Databases. The Mozilla RKV crates depend on an inactive crate, and heed is more maintained and supports more LMDB features.

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey, @nicoburns 👋 Do you need anything else to merge this PR? Have a good day

**Comment by nicoburns** [comment]
Hmm.... heed does seem to be the most actively maintained lmdb library. But I'm a little reluctant to recommend a library whose only recent releases are alphas. Is there a reason why there hasn't been a stable release recently?

**Comment by Kerollmops** [comment]
> heed does seem to be the most actively maintained LMDB library.

[According to lib.rs](https://lib.rs/search?q=lmdb), not all the LMDB wrapper libraries are maintained as much as heed, which seems a lot of activities, fixes, and support for all the LMDB features, e.g., all cursor operations and database settings. Do you think about a more actively maintained and successful LMDB wrapper in the Rust ecosystem?

> Is there a reason why there hasn't been a stable release recently?

There are two reasons for that:
 - The first one is that I release alphas to ensure the API fits most of the users; if I get complaints, I fix the API. After some time, if no issue is opened about the API, I can decide to do a release.
 - The second one is primarily due to time; we actively use heed in Meilisearch. I tried the latest alphas in this big codebase, and releasing a final v0.20 version wasn't the priority as it was working well so far.

You made a good point: It is time to release v0.20, and nobody is complaining about the API anymore. The codebase is great, although not perfect, but very good. The latest issues in the v0.20 milestone will be moved to another future release 🙌

**Comment by Kerollmops** [comment]
Hey @nicoburns 👋

[I finally released Heed v0.20 🛁](https://github.com/meilisearch/heed/releases/tag/v0.20.0). I released a lot of alpha versions, and I finally put an end to that. This is the final, well-maintained, safest, and most popular LMDB wrapper in the Rust ecosystem.

Please, tell me if you need any more information on the matter, if you know any other LMDB wrapper that would be safer and more Rust idiomatic that Heed 😃

Have a nice day 🌻

**Comment by Kerollmops** [comment]
Hey @nicoburns 👋 What do you think now that heed v0.20 has been officially released?

**Comment by Kerollmops** [comment]
Hey @djc 👋 Can we reconsider adding heed to the blessed.rs list? It is the second crate [with more than 74k downloads per month](https://lib.rs/keywords/lmdb), it's the second in the LMDB category after sled (which is not an LMDB wrapper).

**Review by nicoburns — APPROVED** [review]

**Comment by Kerollmops** [comment]
Thank you very much!

**Pull request merged**
